# Generated by Django 4.2.9 on 2024-06-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_socialnetwork_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialnetwork',
            unique_together={('account', 'channel')},
        ),
    ]
